Repository godaddy-wordpress/go, pull requests merged in 2019-10, with the labels that each got.

#368 Tweak media player scrub bar and volume background colors
  .dev/assets/shared/css/elements/media.css
Labels: design

#380 Prep for 1.1.1 release
  .gitignore
  README.md
  comments.php
  composer.json
  composer.lock
  functions.php
  package.json
  readme.txt
  style.css
Labels: wp.org

#385 Introduce breadcrumbs and post navigation in single product templates
  .dev/assets/shared/css/style-shared.css
  .dev/assets/shared/css/woocommerce/single-product.css
  .dev/assets/shared/images/arrow-left.svg
  .dev/assets/shared/images/arrow-right.svg
  .dev/assets/shared/images/close.svg
  .dev/assets/shared/images/empty-cart.svg
  includes/woocommerce.php
Labels: enhancement, woocommerce

#386 Increase page template width for WooCommerce cart and checkout pages
  .dev/assets/shared/css/woocommerce/cart.css
  includes/template-tags.php
  partials/content-excerpt.php
  partials/content-none.php
  partials/content-page.php
  partials/content.php
Labels: woocommerce

#387 Fix archive page title output
  includes/core.php
Labels: cleanup

#388 Tweak product navigation
  .dev/assets/shared/css/woocommerce/single-product.css
  .dev/assets/shared/images/arrow-left.svg
  .dev/assets/shared/images/arrow-right.svg
  includes/woocommerce.php
Labels: cleanup

#393 Fix empty cart message icon
  includes/woocommerce.php
Labels: bug, woocommerce

#395 Update comments in design style CSS files
  .dev/assets/design-styles/playful/css/style-playful.css
  .dev/assets/design-styles/trendy/css/style-trendy.css
  .dev/assets/design-styles/welcoming/css/style-welcoming-editor.css
  .dev/assets/design-styles/welcoming/css/style-welcoming.css
Labels: cleanup

#396 Fix Playful design style default header text color
  includes/core.php
Labels: [Style] Playful, bug

#398 Add variants to --header-padding values
  .dev/assets/design-styles/modern/settings.css
  .dev/assets/design-styles/playful/settings.css
  .dev/assets/design-styles/trendy/settings.css
  .dev/assets/design-styles/welcoming/settings.css
  .dev/assets/shared/css/header/header-4.css
  .dev/assets/shared/css/header/header.css
  .dev/assets/shared/css/header/header__navigation-mobile.css
Labels: enhancement

#392 Introduce WooCommerce cart menu icon
  .dev/assets/design-styles/modern/css/style-modern.css
  .dev/assets/shared/css/header/header-2.css
  .dev/assets/shared/css/header/header-3.css
  .dev/assets/shared/css/header/header-4.css
  .dev/assets/shared/css/header/header.css
  .dev/assets/shared/css/header/header__cart-toggle.css
  .dev/assets/shared/css/header/header__nav-toggle.css
  .dev/assets/shared/css/header/header__search-toggle.css
  .dev/assets/shared/css/style-shared.css
  .dev/assets/shared/images/cart.svg
  header.php
  includes/template-tags.php
  includes/woocommerce.php
Labels: woocommerce

#389 Fix shop title visibility
  .dev/assets/admin/js/customize/preview/page-titles.js
  includes/template-tags.php
  includes/woocommerce.php
Labels: cleanup, woocommerce
