Repository godaddy-wordpress/go, pull requests merged in 2019-11, with the labels that each got.

#403 Fix submenu item word wrap
  .dev/assets/shared/css/header/sub-menu.css
Labels: all styles, bug

#401 Fix Playful design style header text color
  includes/core.php
Labels: [Style] Playful, bug

#394 Tweak variation styles. Update 'Clear' reset variations link text.
  .dev/assets/design-styles/welcoming/css/style-welcoming.css
  .dev/assets/design-styles/welcoming/css/woocommerce/product.css
  .dev/assets/shared/css/woocommerce/product.css
  includes/woocommerce.php
Labels: woocommerce

#400 Improved site search bar
  .dev/assets/design-styles/modern/css/style-modern.css
  .dev/assets/shared/css/header/header-4.css
  .dev/assets/shared/css/header/header.css
  .dev/assets/shared/css/header/header__nav-toggle.css
  .dev/assets/shared/css/header/header__navigation-mobile.css
  .dev/assets/shared/css/header/header__navigation.css
  .dev/assets/shared/css/header/header__search-toggle.css
  .dev/assets/shared/css/header/header__titles.css
  .dev/assets/shared/css/header/search-modal.css
  .dev/assets/shared/css/header/site-search.css
  .dev/assets/shared/css/style-shared.css
  .dev/assets/shared/js/frontend/components/search-toggle.js
  header.php
  includes/template-tags.php
  partials/modal-search.php
  searchform.php
Labels: enhancement

#410 Remove PHPCS suppression
  functions.php
Labels: cleanup

#408 Remove array() in favor of [] syntax
  comments.php
  includes/customizer.php
  includes/template-tags.php
  partials/content.php
  partials/footers/footer-3.php
  partials/footers/footer-4.php
  partials/pagination.php
Labels: cleanup

#407 Add an aria-label to the navigation cart link
  includes/woocommerce.php
Labels: accessibility

#414 Remove PHP array shorthand syntax
  comments.php
  header.php
  includes/classes/customizer/class-switcher-control.php
  includes/core.php
  includes/customizer.php
  includes/pluggable.php
  includes/template-tags.php
  includes/tgm.php
  includes/woocommerce.php
  partials/content-none.php
  partials/content.php
  partials/footers/footer-1.php
  partials/footers/footer-2.php
  partials/footers/footer-3.php
  partials/footers/footer-4.php
  partials/pagination.php
Labels: cleanup

#411 Update unit test suite
  .circleci/config.yml
  .codeclimate.yml
  .dev/tests/php/assets/es_ES.mo
  .dev/tests/php/bootstrap.php
  .dev/tests/php/classes/customizer/test-class-range-control.php
  .dev/tests/php/classes/customizer/test-class-switcher-control.php
  .dev/tests/php/test-core.php
  .dev/tests/php/test-customizer.php
  .dev/tests/php/test-example.php
  .dev/tests/php/test-functions.php
  .dev/tests/php/test-pluggable.php
  .dev/tests/php/test-template-tags.php
  .dev/tests/php/test-tgm.php
  .dev/tests/php/test-woocommerce.php
  .gitignore
  Gruntfile.js
  README.md
  comments.php
  composer.json
  includes/classes/customizer/class-switcher-control.php
  includes/core.php
  includes/customizer.php
  includes/template-tags.php
  includes/tgm.php
  includes/woocommerce.php
  package-lock.json
  partials/pagination.php
  phpunit.xml
Labels: ci/cd, enhancement, testing

#415 Updates to Code Climate config & README.md
  .codeclimate.yml
  README.md
Labels: enhancement

#417 Fix unscoped jQuery breaking editor styles in WP 5.3
  .dev/assets/admin/js/block-filters.js
Labels: cleanup, editor

#418 Fix header regression for absolute positioning
  .dev/deploy-scripts/install-wp-tests.sh
  header.php
Labels: bug

#391 Introduce a WooCommerce slide out cart
  .dev/assets/shared/css/style-shared.css
  .dev/assets/shared/css/woocommerce/button.css
  .dev/assets/shared/css/woocommerce/slideout-menu.css
  .dev/assets/shared/images/shopping-bag.svg
  .dev/assets/shared/js/frontend/components/woo-menu-cart.js
  .dev/assets/shared/js/frontend/frontend.js
  .dev/tests/php/test-woocommerce.php
  includes/woocommerce.php
Labels: enhancement, woocommerce
