Repository godaddy-wordpress/go, pull requests merged in 2020-11, with the labels that each got.

#594 Update Poppins font-weight to 600
  includes/core.php
Labels: [Priority] High, [Status] Needs Review

#591 Update content.php
  partials/content.php
Labels: [Type] Enhancement

#603 Use proper font settings in Playful
  .dev/assets/design-styles/playful/settings.scss
Labels: [Type] Bug

#601 Hide default select field arrow
  .dev/assets/shared/css/elements/forms.scss
Labels: [Type] Enhancement

#599 Add font-display: swap; property
  .dev/assets/shared/css/blocks/events/_style.scss
  .dev/assets/shared/css/blocks/form/_editor.scss
  .dev/assets/shared/css/blocks/pricing-table/_style.scss
  .dev/assets/shared/css/blocks/pullquote/_style.scss
  .dev/assets/shared/css/blocks/quote/_style.scss
  .dev/assets/shared/css/components/comments.scss
  .dev/assets/shared/css/config/mixins.scss
  .dev/assets/shared/css/editor/title-block.scss
  .dev/assets/shared/css/elements/headings.scss
  .dev/assets/shared/css/elements/labels.scss
  .dev/assets/shared/css/elements/page.scss
  .dev/assets/shared/css/elements/typography.scss
  .dev/assets/shared/css/footer/footer-1.scss
  .dev/assets/shared/css/footer/footer-2.scss
  .dev/assets/shared/css/footer/site-footer.scss
  .dev/assets/shared/css/gravity/forms.scss
  .dev/assets/shared/css/header/header__navigation.scss
  .dev/assets/shared/css/header/header__titles.scss
  .dev/assets/shared/css/layout/pagination.scss
  .dev/assets/shared/css/layout/post.scss
  .dev/assets/shared/css/style-editor.scss
  .dev/assets/shared/css/woocommerce/onsale.scss
  .dev/assets/shared/css/woocommerce/shop.scss
  .dev/assets/shared/css/woocommerce/typography.scss
Labels: [Type] Enhancement

#609 Update Cypress to 5.6.0
  package-lock.json
  package.json
Labels: [Type] Enhancement, [Type] Tooling

#608 Touchup styles
  .dev/assets/design-styles/playful/css/blocks/separator.scss
  .dev/assets/shared/css/blocks/blocks.scss
  .dev/assets/shared/css/blocks/hero/_style.scss
  .dev/assets/shared/css/blocks/image/_style.scss
  .dev/assets/shared/css/blocks/latest-comments/_style.scss
  .dev/assets/shared/css/blocks/latest-posts/_style.scss
  .dev/assets/shared/css/blocks/masonry/_style.scss
  .dev/assets/shared/css/blocks/more/_style.scss
  .dev/assets/shared/css/blocks/pricing-table/_style.scss
  .dev/assets/shared/css/blocks/pullquote/_style.scss
  .dev/assets/shared/css/blocks/quote/_style.scss
  .dev/assets/shared/css/blocks/search/_style.scss
  .dev/assets/shared/css/blocks/services/_style.scss
  .dev/assets/shared/css/blocks/social/_style.scss
  .dev/assets/shared/css/blocks/table/_editor.scss
  .dev/assets/shared/css/blocks/table/_style.scss
  .dev/assets/shared/css/blocks/video/_style.scss
  .dev/assets/shared/css/blocks/woocommerce/_editor.scss
  .dev/assets/shared/css/editor/horizontal-rhythm.scss
  .dev/assets/shared/css/editor/vertical-rhythm.scss
  .dev/assets/shared/css/layout/alignments.scss
Labels: [Priority] High, [Status] Needs Review

#611 Fix submenu hover regression introduced in 1.3.7
  .dev/assets/shared/css/header/sub-menu.scss
  .dev/tests/php/test-core.php
  .dev/tests/php/test-woocommerce.php
  comments.php
  includes/pluggable.php
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#598 Fix visibility of WooCommerce checkboxes and radios
  .dev/assets/shared/css/woocommerce/blocks.scss
  .dev/assets/shared/css/woocommerce/button.scss
  .dev/assets/shared/css/woocommerce/cart.scss
  .dev/assets/shared/css/woocommerce/checkbox.scss
  .dev/assets/shared/css/woocommerce/forms.scss
  .dev/assets/shared/css/woocommerce/notice.scss
  .dev/assets/shared/css/woocommerce/pagination.scss
  .dev/assets/shared/css/woocommerce/product.scss
  .dev/assets/shared/css/woocommerce/radio.scss
  .dev/assets/shared/css/woocommerce/shop.scss
  .dev/assets/shared/css/woocommerce/single-product.scss
  .dev/assets/shared/css/woocommerce/slideout-menu.scss
Labels: [Type] Enhancement

#607 Improve the cart template
  .dev/assets/shared/css/woocommerce/cart.scss
  languages/go.pot
  woocommerce/cart/cart.php
Labels: [Type] Enhancement

#606 Add underline to WooCommerce product title on hover
  .dev/assets/shared/css/woocommerce/product.scss
Labels: [Type] Enhancement

#616 Remove invalid HSL styles
  .dev/assets/shared/css/header/header-4.scss
  .dev/assets/shared/css/header/header__navigation-mobile.scss
  .dev/assets/shared/css/header/search-modal.scss
Labels: [Priority] Low, [Status] Needs Review

#615 Tweak margin, spacing of product in cart
  .dev/assets/shared/css/woocommerce/cart.scss
Labels: [Type] Enhancement

#602 Fix variable product quantity/submit button height
  .dev/assets/shared/css/woocommerce/product.scss
Labels: [Type] Enhancement

#614 Improve cover block styles
  .dev/assets/shared/css/blocks/cover/_style.scss
  .dev/assets/shared/css/utilities/colors.scss
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement
