Repository godaddy-wordpress/go, pull requests merged in 2020-07, with the labels that each got.

#550 Apply :root to better prevent Gutenberg overriding theme colors.
  .dev/assets/shared/css/utilities/colors.css
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#556 Fix block editor inserter panel pattern styles
  .dev/assets/shared/css/style-editor.css
Labels: [Status] Needs Review

#553 Update post meta tags wrapper CSS
  .dev/assets/shared/css/layout/post.css
Labels: [Type] Design

#552 Fix one column product grid
  .dev/assets/shared/css/style-editor.css
  .dev/assets/shared/css/woocommerce/blocks.css
  .dev/assets/shared/css/woocommerce/product.css
  .dev/assets/shared/css/woocommerce/shop.css
Labels: [Priority] Low, [Type] Woo

#559 Update styles for Cover block positioning in WordPress 5.5
  .dev/assets/shared/css/blocks/cover.css
Labels: [Priority] High
