Repository godaddy-wordpress/go, pull requests merged in 2020-01, with the labels that each got.

#431 Fix PHPUnit tests
  .dev/tests/php/bootstrap.php
  .dev/tests/php/test-template-tags.php
  .dev/tests/php/test-woocommerce.php
  includes/woocommerce.php
Labels: ci/cd, testing

#434 Rename Colors customizer panel to Site Design
  .dev/tests/php/test-customizer.php
  includes/customizer.php
Labels: customizer

#430 Update typography.css
  .dev/assets/shared/css/elements/typography.css
Labels: cleanup

#436 Update screenshot and add license for the image
  readme.txt
  screenshot.png
Labels: cleanup

#437 WordPress.org theme review fixes
  .dev/assets/design-styles/modern/css/style-modern.css
  .dev/assets/design-styles/traditional/css/style-traditional.css
  .dev/assets/shared/css/layout/post.css
  .dev/assets/shared/images/author.svg
  .dev/assets/shared/images/bookmark.svg
  .dev/assets/shared/images/categories.svg
  .dev/assets/shared/images/comments.svg
  .dev/assets/shared/images/social/facebook.svg
  .dev/assets/shared/images/social/instagram.svg
  .dev/assets/shared/images/social/linkedin.svg
  .dev/assets/shared/images/social/pinterest.svg
  .dev/assets/shared/images/social/twitter.svg
  .dev/assets/shared/images/tags.svg
  .dev/assets/shared/js/frontend/components/primary-menu.js
  .dev/assets/shared/js/frontend/components/search-toggle.js
  includes/tgm.php
  readme.txt
  searchform.php
Labels: wp.org

#439 Add jQuery as a dependency of frontend.js, update readme for 1.2.3
  includes/core.php
  readme.txt
Labels: bug, wp.org

#440 Remove awaiting approval note from readme.md
  README.md
Labels: cleanup

#449 Prevent site header from overlapping the mobile menu
  .dev/assets/shared/css/header/header.css
Labels: all styles, enhancement

#435 Introduce RTL support
  .dev/assets/design-styles/modern/settings.css
  .dev/assets/design-styles/traditional/settings.css
  .dev/assets/shared/css/blocks/gallery.css
  .dev/assets/shared/css/coblocks/masonry.css
  .dev/assets/shared/css/utilities/captions.css
  .dev/config/webpack.dev.js
  .dev/deploy-scripts/tweak-css-files.sh
  includes/core.php
  includes/customizer.php
  package-lock.json
  package.json
Labels: all styles, enhancement

#445 Conditionally set menu locations description based on selected footer variation
  .dev/assets/admin/js/customize/preview/footer.js
Labels: customizer

#453 Introduce canary job into CircleCI
  .circleci/config.yml
Labels: [Status] In Progress, [Type] Enhancement, [Type] Tooling

#457 Fix canary release title
  .circleci/config.yml
Labels: [Type] Bug, [Type] Tooling
