Repository godaddy-wordpress/go, pull requests merged in 2020-05, with the labels that each got.

#516 Vertical alignment + block spacing tweaks
  .dev/assets/shared/css/blocks/columns.css
  .dev/assets/shared/css/blocks/group.css
  .dev/assets/shared/css/blocks/image.css
  .dev/assets/shared/css/blocks/quote.css
  .dev/assets/shared/css/editor/vertical-rhythm.css
  .dev/assets/shared/css/elements/headings.css
  .dev/assets/shared/css/elements/typography.css
  .dev/assets/shared/css/layout/alignments.css
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#515 Imrpove documentation, helping new users onboard into developing with Go
  .dev/assets/development-environment.php
  .dev/deploy-scripts/local-install-wp-tests.sh
  .dev/tests/php/test-core.php
  composer.json
  docs/design-styles/design-styles.md
  docs/design-styles/example/example.md
  docs/design-styles/properties.md
  docs/development-environment.md
  includes/core.php
Labels: [Type] Docs

#521 Add tested up to/requires php to style.css headers
  style.css
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Enhancement

#523 Set the customizer color palettes to the currently selected color scheme
  .dev/assets/admin/js/customize-controls.js
  .dev/assets/admin/js/customize/controls/set-active-color-schemes.js
  includes/customizer.php
Labels: [Type] Enhancement

#511 Add ability to toggle page titles on and off
  .babelrc
  .dev/assets/admin/js/block-filters.js
  .dev/config/webpack.common.js
  .dev/tests/php/test-template-tags.php
  .dev/tests/php/test-title-meta.php
  functions.php
  includes/core.php
  includes/customizer.php
  includes/template-tags.php
  includes/title-meta.php
  languages/go.pot
  package-lock.json
  package.json
Labels: [Status] Do Not Merge, [Status] In Progress, [Type] Enhancement

#525 Introduce color scheme gradients
  includes/core.php
  includes/customizer.php
Labels: [Type] Enhancement

#526 Additional design tweaks
  .dev/assets/shared/css/blocks/quote.css
  .dev/assets/shared/css/editor/vertical-rhythm.css
Labels: [Priority] Low, [Status] Needs Review

#522 [Fix] Use `display_name` for the post author section.
  includes/template-tags.php
Labels: [Type] Enhancement
