Repository godaddy-wordpress/go, pull requests merged in 2020-03, with the labels that each got.

#473 Bump tested up to version to 5.4
  README.md
  readme.txt
Labels: [Status] Ready to Merge

#478 Improve npm run watch with flags
  .dev/config/webpack.dev.js
  package-lock.json
  package.json
Labels: [Type] Enhancement

#469 Fix Welcoming design style page with featured image
  .dev/assets/shared/css/layout/featured-image.css
Labels: [Status] Ready to Merge, [Type] Design

#475 Add changelog.txt update release notes with latest changes
  .circleci/config.yml
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, [Type] Enhancement, [Type] Tooling

#471 Updates for AMP support
  header.php
  includes/template-tags.php
Labels: [Type] Enhancement

#477 Fix checkbox and radio visibility
  .dev/assets/shared/css/config/mixins.css
  .dev/assets/shared/css/elements/forms.css
Labels: [Status] Ready to Merge, [Type] Bug

#476 Update styles for WooCommerce 4.0 block compatibility
  .dev/assets/shared/css/editor/woocommerce-blocks.css
  .dev/assets/shared/css/elements/forms.css
  .dev/assets/shared/css/style-editor.css
  .dev/assets/shared/css/woocommerce/blocks.css
  .dev/assets/shared/css/woocommerce/button.css
  .dev/assets/shared/css/woocommerce/shop.css
Labels: [Status] Needs Review, [Type] Design, [Type] Woo

#482 Bump .header z-index higher
  .dev/assets/shared/css/header/header.css
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Design

#481 Update copyright footer text
  .dev/tests/php/test-core.php
  .dev/tests/php/test-template-tags.php
  includes/core.php
  includes/template-tags.php
Labels: [Status] Needs Review

#468 Update copyright footer text
  .dev/tests/php/test-core.php
  .dev/tests/php/test-customizer.php
  .dev/tests/php/test-template-tags.php
  includes/customizer.php
  includes/template-tags.php
Labels: [Status] Needs Review, [Type] Enhancement

#484 Update the Canary build deploy job
  .circleci/config.yml
Labels: [Type] Enhancement

#485 Resolve specificity issue with the group block within the editor
  .dev/assets/shared/css/editor/group.css
Labels: [Priority] High, [Type] Bug

#490 Add doc + example for extending design styles
  .distignore
  docs/design-styles/design-styles.md
  docs/design-styles/example/example.md
  docs/design-styles/example/functions.php
  docs/design-styles/example/style-brutalist.css
  docs/design-styles/properties.md
Labels: [Type] Docs
