Repository godaddy-wordpress/go, pull requests merged in 2020-06, with the labels that each got.

#528 Fix gradient control
  .dev/tests/php/test-template-tags.php
  .dev/tests/php/test-title-meta.php
  includes/core.php
  includes/template-tags.php
  includes/title-meta.php
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#524 Add layouts for use with CoBlocks layout selector
  functions.php
  partials/layouts/about.php
  partials/layouts/contact.php
  partials/layouts/home.php
  partials/layouts/images/1x1.jpg
  partials/layouts/images/2x3.jpg
  partials/layouts/portfolio.php
Labels: [Status] Needs Review, [Type] Enhancement

#532 Add wrapper and styles for more block
  .dev/assets/shared/css/blocks/more.css
  .dev/assets/shared/css/elements/buttons.css
  .dev/tests/php/test-core.php
  includes/core.php
Labels: [Priority] Low, [Status] Needs Review

#533 Add minor style fixes
  .dev/assets/shared/css/editor/group.css
  .dev/assets/shared/css/layout/alignments.css
  .dev/assets/shared/css/style-editor.css
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug

#534 Tweak svgs for improved accessibility
  .dev/assets/shared/images/author.svg
  .dev/assets/shared/images/bookmark.svg
  .dev/assets/shared/images/calendar.svg
  .dev/assets/shared/images/categories.svg
  .dev/assets/shared/images/comments.svg
  .dev/assets/shared/images/social/facebook.svg
  .dev/assets/shared/images/social/github.svg
  .dev/assets/shared/images/social/instagram.svg
  .dev/assets/shared/images/social/linkedin.svg
  .dev/assets/shared/images/social/pinterest.svg
  .dev/assets/shared/images/social/twitter.svg
  .dev/assets/shared/images/social/youtube.svg
  .dev/assets/shared/images/tags.svg
  includes/template-tags.php
Labels: [Status] Needs Review, [Type] Enhancement, [Type] a11y

#537 Add cypress.json to the distignore
  .circleci/config.yml
  .distignore
Labels: [Priority] Low

#540 Fix checkout radio buttons
  .dev/assets/shared/css/style-shared.css
  .dev/assets/shared/css/woocommerce/radio.css
Labels: [Type] Bug
