Repository godaddy-wordpress/go, pull requests merged in 2020-04, with the labels that each got.

#491 Design style improvements
  .dev/assets/design-styles/playful/settings.css
  .dev/assets/design-styles/trendy/settings.css
  .dev/assets/design-styles/welcoming/css/style-welcoming.css
  .dev/assets/design-styles/welcoming/settings.css
  .dev/assets/shared/css/config/mixins.css
  .dev/assets/shared/css/elements/forms.css
  .dev/assets/shared/css/footer/site-footer.css
  .dev/assets/shared/css/gravity/forms.css
  .dev/assets/shared/css/header/header-4.css
  .dev/assets/shared/css/header/header.css
  .dev/assets/shared/css/header/header__cart-toggle.css
  .dev/assets/shared/css/header/header__nav-toggle.css
  .dev/assets/shared/css/header/header__navigation-mobile.css
  .dev/assets/shared/css/header/header__search-toggle.css
  .dev/assets/shared/css/header/search-modal.css
  .dev/assets/shared/css/woocommerce/forms.css
Labels: [Priority] Low, [Type] Design

#480 Update editor styles for Gutenberg 7.7
  .dev/assets/shared/css/blocks/gallery.css
  .dev/assets/shared/css/editor/vertical-rhythm.css
Labels: [Priority] High

#497 Fix copyright footer text save error
  includes/customizer.php
Labels: [Type] Bug

#493 Allow design styles to enqueue no Google fonts
  includes/core.php
Labels: [Type] Enhancement

#498 Declare HTML5 scripts and styles support for better compliance with W3C validator
  includes/core.php
Labels: [Type] Enhancement

#488 Enhance the slide out cart
  .dev/assets/shared/css/woocommerce/button.css
  .dev/assets/shared/css/woocommerce/slideout-menu.css
  includes/woocommerce.php
Labels: [Type] Enhancement

#502 Deploy canary build to wpnux
  .circleci/config.yml
Labels: [Type] Tooling

#501 Remove customize-preview dependency from go-customize-preview
  includes/customizer.php
Labels: [Priority] High, [Type] Bug

#500 Add color controls to Site Design panel
  .dev/assets/admin/css/style-customize.css
  .dev/assets/admin/js/customize-controls.js
  .dev/tests/php/classes/customizer/test-title-control.php
  .dev/tests/php/test-customizer.php
  includes/classes/customizer/class-title-control.php
  includes/customizer.php
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#509 Try improved spacing styles
  .dev/assets/design-styles/playful/css/style-playful.css
  .dev/assets/design-styles/trendy/css/style-trendy.css
  .dev/assets/shared/css/blocks/gallery.css
  .dev/assets/shared/css/blocks/group.css
  .dev/assets/shared/css/blocks/image.css
  .dev/assets/shared/css/blocks/separator.css
  .dev/assets/shared/css/editor/vertical-rhythm.css
  .dev/assets/shared/css/footer/footer-2.css
  .dev/assets/shared/css/footer/footer-4.css
  .dev/assets/shared/css/footer/site-footer.css
  .dev/assets/shared/css/layout/alignments.css
  .dev/assets/shared/css/layout/content.css
  .dev/assets/shared/css/style-editor.css
  .dev/assets/shared/css/style-shared.css
  .dev/tests/php/test-core.php
  404.php
  includes/core.php
  partials/content-excerpt.php
  partials/content-none.php
  partials/content-page.php
  partials/content.php
Labels: [Priority] High, [Status] In Progress

#513 Resolve featured image text color bug
  .dev/assets/shared/css/layout/featured-image.css
Labels: [Priority] High, [Type] Bug

#512 Add viewport basis Customizer controls
  .dev/assets/admin/css/style-customize.css
  .dev/tests/php/test-customizer.php
  includes/customizer.php
Labels: [Status] Needs Review, [Type] Enhancement

#514 Add Events block styles to shared theme styles
  .dev/assets/shared/css/coblocks/events.css
  .dev/assets/shared/css/style-editor.css
  .dev/assets/shared/css/style-shared.css
Labels: [Type] Bug
