Repository godaddy-wordpress/go, pull requests merged in 2020-08, with the labels that each got.

#541 Add new experimental link color theme support
  .dev/assets/shared/css/blocks/paragraph.css
  includes/core.php
Labels: [Priority] Low, [Status] Do Not Merge, [Status] In Progress, [Type] Enhancement

#563 Fix: Group block's custom padding was not reflected in the editor
  .dev/assets/shared/css/blocks/group.css
  .dev/assets/shared/css/editor/group.css
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug

#564 Fix header background fallback issue
  .dev/assets/design-styles/playful/settings.css
  .dev/assets/design-styles/welcoming/css/style-welcoming.css
  .dev/assets/design-styles/welcoming/settings.css
  .dev/assets/shared/css/header/header.css
Labels: [Priority] Low, [Status] Needs Review

#561 Update style to ignore the future Media & Text card style
  .dev/assets/shared/css/blocks/media.css
Labels: [Priority] Low, [Type] Enhancement, [Type] Gutenberg

#566 Bump tested up to version to 5.5
  README.md
  readme.txt
Labels: [Priority] High

#568 Update changelog and readme files to indicate 5.5 support
  changelog.txt
  readme.txt
Labels: [Type] Docs

#572 Add e-commerce tag to readme.txt/style.css
  readme.txt
  style.css
Labels: [Status] Needs Review, [Type] Enhancement
