Repository godaddy-wordpress/go, pull requests merged in 2020-02, with the labels that each got.

#460 Fix CircleCI branches
  .circleci/config.yml
Labels: [Type] Tests

#463 Tweak labels
  .github/labels.yml
  .github/workflows/labeler.yml
Labels: [Priority] Low, [Type] Maintenance

#464 Hide previously open menu items when a new one is opened
  .dev/assets/shared/js/frontend/vendor/responsive-nav.js
Labels: [Priority] High, [Status] Needs Review, [Type] Enhancement

#461 Fix gallery caption alignment
  .dev/assets/shared/css/blocks/gallery.css
Labels: [Type] Design

#452 Tweak CoBlocks carousel block arrows for Welcoming, Trendy and Playful design styles
  .dev/assets/design-styles/modern/css/components/carousel.css
  .dev/assets/design-styles/playful/css/components/carousel.css
  .dev/assets/design-styles/traditional/css/style-traditional.css
  .dev/assets/design-styles/trendy/css/components/carousel.css
  .dev/assets/design-styles/welcoming/css/components/carousel.css
Labels: [Priority] Low, [Type] Design

#451 Try improved vertical rhythm
  .dev/assets/design-styles/modern/settings.css
  .dev/assets/design-styles/playful/settings.css
  .dev/assets/design-styles/traditional/settings.css
  .dev/assets/design-styles/trendy/settings.css
  .dev/assets/design-styles/welcoming/settings.css
Labels: [Priority] High, [Status] Needs Review, [Type] Enhancement
