Repository godaddy-wordpress/go, pull requests merged in 2021-11, with the labels that each got.

#709 Fix WooCommerce shop button styles, and success message styles on cart
  .dev/assets/shared/css/woocommerce/button.scss
  .dev/assets/shared/css/woocommerce/notice.scss
  .dev/assets/shared/css/woocommerce/shop.scss
Labels: [Priority] Low, [Status] Needs Review, [Type] Woo, [Type] Design

#712 Add ability to set header to sticky
  .dev/assets/shared/css/header/header-6.scss
  .dev/assets/shared/css/header/header.scss
  .dev/assets/shared/css/layout/entry-header.scss
  includes/core.php
  includes/customizer.php
  package.json
  yarn.lock
Labels: [Type] Enhancement

#728 Add polyfill and rebuild composer.lock
  composer.json
  composer.lock
Labels: [Type] Bug, [Priority] High

#731 Attach artifacts and provide download link
  .circleci/config.yml
  .dev/bin/comment-on-pr.sh
Labels: [Type] Enhancement, [Type] Tooling

#733 Fix PR comment, edit last bot comment only
  .dev/bin/comment-on-pr.sh
Labels: [Type] Enhancement, [Type] Tooling
