Repository godaddy-wordpress/go, pull requests merged in 2021-04, with the labels that each got.

#655 Fix header 2 submenu alignment
  .dev/assets/shared/css/header/header-2.scss
Labels: [Priority] Low, [Status] Needs Review

#656 Remove the 16px bottom margin from the last-child image in a gallery
  .dev/assets/shared/css/blocks/gallery/_style.scss
Labels: [Priority] Low, [Status] Needs Review

#657 Make Modern design style Heebo font the default
  .dev/tests/php/test-core.php
  includes/core.php
Labels: [Type] Enhancement

#658 Allow for logo, title and tagline to display
  .dev/assets/shared/css/header/header-2.scss
  .dev/assets/shared/css/header/header-3.scss
  .dev/assets/shared/css/header/header-4.scss
  .dev/assets/shared/css/header/header__titles.scss
  includes/template-tags.php
Labels: [Status] Needs Review, [Type] Enhancement

#652 Fix invalid rgb color string
  .dev/tests/php/test-customizer.php
  .dev/tests/php/test-template-tags.php
  includes/core.php
  includes/template-tags.php
Labels: [Priority] High

#660 Fix modern tagline
  .dev/assets/design-styles/modern/settings.scss
  .dev/assets/shared/css/header/header__titles.scss
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug, [Type] Design
