Repository godaddy-wordpress/go, pull requests merged in 2021-02, with the labels that each got.

#636 Tweak Modern styles for WooCommerce (mobile and desktop)
  .dev/assets/design-styles/modern/css/style-modern.scss
Labels: [Status] Needs Review, [Type] Bug, [Type] Woo

#638 Enable post categories
  includes/template-tags.php
Labels: [Type] Enhancement

#639 Change portfolio to gallery
  .nprc
  package-lock.json
  partials/layouts/gallery.php
Labels: [Type] Enhancement

#630 Tweak mobile functionality on mobile
  .dev/assets/shared/css/header/header-4.scss
  .dev/assets/shared/css/header/header__navigation-mobile.scss
  .dev/assets/shared/css/header/sub-menu.scss
  .dev/assets/shared/js/frontend/vendor/responsive-nav.js
  .dev/tests/php/test-core.php
  .dev/tests/php/test-template-tags.php
  includes/core.php
Labels: [Type] Enhancement

#631 Re-enable checkbox images
  .dev/assets/shared/css/config/mixins.scss
  .dev/assets/shared/css/elements/forms.scss
  .dev/tests/php/test-template-tags.php
Labels: [Status] Needs Review

#643 Try using PHP 7.4
  .circleci/config.yml
  .dev/deploy-scripts/install-wp-tests.sh
  composer.json
  composer.lock
  package-lock.json
Labels: [Type] Tests
