Repository godaddy-wordpress/go, pull requests merged in 2022-01, with the labels that each got.

#746 Fix build path to images
  .dev/config/webpack.settings.js
Labels: [Priority] High

#750 Bump tested up to 5.9
  docs/design-styles/example/functions.php
  readme.txt
  style.css
Labels: [Priority] High

#739 #738 Add TikTok Option
  .dev/assets/admin/js/customize/preview/footer.js
  .dev/assets/shared/images/social/tiktok.svg
  .dev/tests/cypress/integration/customizer/customizer.spec.js
  .dev/tests/php/test-core.php
  .dev/tests/php/test-customizer.php
  .dev/tests/php/test-template-tags.php
  includes/core.php
  languages/go.json
  languages/go.pot
Labels: [Type] Enhancement

#725 Fix spacing in config and enable phpcs cache
  .circleci/config.yml
  changelog.txt
  docs/child-theme/functions.php
  phpcs.xml
  readme.txt
Labels: [Type] Enhancement, [Type] Tooling
