Repository godaddy-wordpress/go, pull requests merged in 2022-11, with the labels that each got.

#817 Bump the cart.php template version
  woocommerce/cart/cart.php
Labels: [Type] Enhancement, [Type] Woo

#814 Add label styles to site design stylesheets
  .dev/assets/design-styles/playful/settings.scss
  .dev/assets/design-styles/traditional/settings.scss
Labels: [Status] Needs Review

#819 Update change log for 1.6.6 release
  changelog.txt
  readme.txt
Labels: [Type] Enhancement
