Repository godaddy-wordpress/go, pull requests merged in 2022-07, with the labels that each got.

#794 Apple pay style conflict with go
  .dev/assets/shared/css/woocommerce/button.scss
Labels: [Type] Enhancement, [Type] Woo, [Type] Design

#791 Drop support for PHP 5.6
  .circleci/config.yml
  composer.json
  composer.lock
Labels: [Status] Do Not Merge

#793 Add theme json to enable appearanceTools
  theme.json
Labels: [Type] Enhancement
