Repository godaddy-wordpress/go, pull requests merged in 2023-07, with the labels that each got.

#884 Add cover styles with filter contrast
  .dev/assets/shared/css/blocks/cover/_style.scss
Labels: [Type] Enhancement, [Type] Design

#889 Re-add the original go_avaliable_social_icons filter
  .dev/tests/php/test-core.php
  includes/core.php
Labels: [Type] Enhancement

#894 Update CI/CD Pipeline to run Unit Tests
  .dev/tests/php/bootstrap.php
  .github/workflows/update-translations.yml
  composer.json
  composer.lock
  languages/go.json
  languages/go.pot
Labels: [Type] i18n, [Type] Enhancement, [Type] Tests
