Repository godaddy-wordpress/go, pull requests merged in 2023-03, with the labels that each got.

#847 Introduce a script and a Github workflow to ensure our WooCommerce templates are always up to date with the latest version.
  .codeclimate.yml
  .dev/bin/update-woo-template-versions.php
  .github/workflows/bump-woo-template-versions.yml
  package.json
Labels: [Type] Woo

#850 Update workflow badge from CircleCI to Github Actions
  README.md
Labels: [Type] Enhancement, [Priority] Low

#851 Update the circleci badge in the package.json file
  package.json
Labels: [Type] Enhancement

#852 1.8.1
  .dev/tests/php/test-functions.php
  .github/workflows/codeql-analysis.yml
  README.md
  functions.php
  package.json
  readme.txt
  style.css
Labels: [Type] Enhancement
